name: profolio
description: A portfolio and discovery app for high school students.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/temp.jpg
    - lib/assets/images/van-orang.jpg
  fonts:
    - family: WorkSans
      fonts:
        - asset: lib/assets/fonts/worksans.ttf
    - family: Fun
      fonts:
        - asset: lib/assets/fonts/fun.ttf