name: profolio
description: A portfolio and discovery app for high school students.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  printing: ^5.12.0
  provider: ^6.1.2
  screenshot: ^2.3.0

 
  widgets_to_image: ^0.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/App_Icon.png
  fonts:
    - family: SFPro
      fonts:
        - asset: lib/assets/fonts/ProSuperLight.ttf
        - asset: lib/assets/fonts/ProBold.otf
        - asset: lib/assets/fonts/ProLight.otf
        - asset: lib/assets/fonts/ProMedium.otf
        - asset: lib/assets/fonts/ProRegular.otf