name: profolio
description: A portfolio and discovery app for high school students.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/App_Icon.png
  fonts:
    - family: WorkSans
      fonts:
        - asset: lib/assets/fonts/worksans.ttf
    - family: NotoSans
      fonts:
        - asset: lib/assets/fonts/NotoBasic.ttf
        - asset: lib/assets/fonts/NotoBold.ttf